# deve conter todos os comandos utilizados na execuçao desenvolvimento da aplicaçao
all:

pipenv:
	pipenv --three; pipenv shell

pipenv_installs:

pipenv_dev_package:
	pipenv install --dev black; pipenv graph

run_dev:
	

